version: '3'

services:
  app: 
    container_name: "front_back"
    build: 
      context: "."
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:8080
    command: ./main

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: react_go_app
      MYSQL_USER: backend
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --authentication_policy=mysql_native_password
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      #- ./mysql/conf.d/my.conf:/etc/mysql/conf.d/my.cnf #アクセス権限の影響で読み込まれない
      #- ./mysql/mysql_data:/var/lib/mysql #コメントアウトすると、DBをコンテナ建て替えるたびに初期化
    ports:
      - 3306:3306

  phpmyadmin: #MySQLへのアクセス　中身の確認用
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 1234:80
    depends_on:
      - mysql